### ISSUE TITLE
Can you please help with SSH Keys?

### ISSUE THREAD

**Issue by alsolh** [zimmertr/Bootstrap-Kubernetes-with-QEMU#1]
hi dear, thanks for your efforts on this repo. bit of a noob here and wanted to use your playbooks. can you guide us what to do to generate required keys? can i use existing proxmox id_rsa keys located in the root/.ssh folder?

**Comment by zimmertr** [comment]
FYI I have recently purchased new hardware for my homelab and am now free of a lot of technical restrictions. As a result, I am refactoring this project into [TKS](https://github.com/zimmertr/TKS). So this project will have no further development.

However, you should be able to get things working pretty quickly if SSH keys are your only issue. Simply ssh into the Proxmox server and run `ssh-keygen`. Copy the resultant SSH public key to your `~/.ssh/authorized_hosts` file and restart sshd `systemctl restart sshd`. After that, modify `inventory.ini` for this project to point to both the hostname for your Proxmox server as well as update the `ansible_user` and `ansible_ssh_private_key_file` arguments for your new SSH key.

https://github.com/zimmertr/Bootstrap-Kubernetes-with-QEMU/blob/master/inventory.ini

**Comment by zimmertr** [comment]
Feel free to leave another comment if you have further trouble. I'm happy to keep assisting you but I'm going to close this issue for now.

**Comment by alsolh** [comment]
Thanks zimmertr, you may close sure, i will follow you in your new project when i get more experience with kubernetes, for now since i am still new to kubernetes; have decided to go for rancher and rancheros, they are working fine in proxmox with 2 worker nodes and 1 master and didnt take much time to setup
