### ISSUE TITLE
delete_all_resources.yml does not remove the Kubernetes pool

### ISSUE THREAD

**Issue by kifeo** [zimmertr/Bootstrap-Kubernetes-with-QEMU#18]
when using the delete_all_resources.yml, it does not remove the Kubernetes pool that have been created.

**Comment by zimmertr** [comment]
https://github.com/zimmertr/Bootstrap-Kubernetes-with-QEMU/blob/b51c263f0738a3085f5200db1dcfd9f47cf9e782/playbooks/optional/delete_all_resources.yml#L25

It is implemented here and just successfully worked on my system after a test. You may notice that `ignore_errors: yes` is set which allows Ansible to proceed regardless of the success of that task. If you look at the STDOUT of Ansible when you run that command you should see why it is failing on your specific system. Feel free to provide an update with this information and I will reopen this issue.
