### ISSUE TITLE
Typo in bootstrap

### ISSUE THREAD

**Issue by danmanners** [zimmertr/Bootstrap-Kubernetes-with-QEMU#3]
https://github.com/zimmertr/Bootstrap-Kubernetes-with-QEMU/blob/26972f6313defb69a03e1126dba6ded4e87bcd51/playbooks/main/bootstrap_kubernetes.yml#L52

Should be `      - name: Configuring RBAC for the Dashboard service account.`

**Comment by zimmertr** [comment]
Lol PRs are welcome

**Comment by zimmertr** [comment]
FINE DAN I DID IT MYSELF

**Comment by danmanners** [comment]
I'M SORRY TJ I MEANT TO DO THIS AND COMPLETELY FORGOT
