### ISSUE TITLE
Disk resize error

### ISSUE THREAD

**Issue by jtonello** [zimmertr/Bootstrap-Kubernetes-with-QEMU#8]
deploy_qcow2_vms.yml (line 78):

qm resize {{ item.id }} scsi0 {{ item.size }}

This resizing works, but somehow ProxMox doesn't recognize or report the change and Ansible doesn't see it and fails the task. I find if I wait a few minutes, ProxMox (and the dashboard) catch up and show the proper resized value. I get past it by waiting or manually adding 1G to each scsi0 disk in the ProxMox dashboard, and then restarting the playbook after the resize task. All's well from there.

**Comment by zimmertr** [comment]
Hi @jtonello, thanks for opening this issue. As mentioned in your original email I suspect that this issue is related to using an older version of Proxmox. As a result, I am unable to test any fixes that would be introduced accordingly without setting up a secondary server. (For which I have no hardware). 

If you are able to produce a fix and test it accordingly, I would willingly (and happily) test your fix on the newest version of Proxmox and merge it in accordingly.

**Comment by jtonello** [comment]
Hi @zimmert. I'm running 5.3-8 (newest release is 5.4). I'll try to do some
hunting around about the fix and see what I can provide. Thanks again!

**Comment by jtonello** [comment]
Hi Thomas,

I managed to find a fix. I did a couple things:

1. Upgraded ProxMox to the latest version

2. Changed line 88 in playbooks/main/deploy_qcow2_vms.yml

#       shell: qm resize {{ item.id }} scsi0 {{ item.size }}

to
        shell: /usr/bin/qemu-img resize -f raw /storage/images/{{ item.id
}}/vm-{{ item.id }}-disk-0.raw {{ item.size }}

Apparently, the qm syntax calls the qemu-img binary, but it always failed
there. Directly calling qemu-img works. The qemu-img syntax calls for
an *additional
*size, so I used "+30G" intead of "30G" in the vars.yml file.

Also note that my storage path/device is a drive mounted at /storage on the
pve host.

Finally, I notice I needed to add the ".raw" extension to the disk when
referencing them in the deployment YAML file. Perhaps the -t raw syntax is
deprecated?

John

**Comment by zimmertr** [comment]
This is a complicated scenario and the logic that is written for Ansible changes pretty significantly between storage types. For example, doing this with ZFS which is what I develop this software against yields the following result:
```
$ qemu-img resize -f raw /dev/zvol/SaturnPool/vm-40100-disk-0 +30G
qemu-img: Cannot grow device files
```

Furthermore, whether or not the `.raw` extension exists depending on how your storage presents VM images as well. As I am unable to test against other storage types I will not be able to fix this issue without the assistance of someone with multiple storage types available in their environment. Including, at least, ZFS & a locally mounted storage solution such as yours.
